"""Sample data for seeding the MotherSource AI database."""

SEED_ENTITIES = [
    {
        "name": "ASRAM Medical College & Hospital",
        "type": "Medical College",
        "district": "Eluru",
        "state": "Andhra Pradesh",
        "address": "Eluru, West Godavari District, AP",
        "website": "https://asram.edu.in",
        "email": "info@asram.edu.in",
        "phone": "+91-8812-234567",
        "description": "A premier medical college with a 1000-bed hospital providing comprehensive maternal and child health services. Strong obstetrics and gynecology department with dedicated NICU. Serves as a referral center for West Godavari district.",
        "relevance_score": 94.0,
        "priority_score": 91.0,
    },
    {
        "name": "Lotus Hospitals for Women & Children",
        "type": "Private Hospital",
        "district": "Visakhapatnam",
        "state": "Andhra Pradesh",
        "address": "Dwaraka Nagar, Visakhapatnam, AP 530016",
        "website": "https://lotushospitals.in",
        "email": "contact@lotushospitals.in",
        "phone": "+91-891-2567890",
        "description": "Specialized women and children hospital with advanced maternal care, high-risk pregnancy management, and neonatal intensive care unit. Serves over 5000 deliveries annually in Visakhapatnam.",
        "relevance_score": 92.0,
        "priority_score": 89.0,
    },
    {
        "name": "Dhaatri Resource Centre for Women & Children",
        "type": "NGO",
        "district": "Hyderabad",
        "state": "Telangana",
        "address": "Secunderabad, Hyderabad, Telangana",
        "website": "https://dhaatri.org",
        "email": "dhaatri@dhaatri.org",
        "phone": "+91-40-27804923",
        "description": "Dhaatri is a resource center working on women's rights and child rights, focusing on maternal health, nutrition, and breastfeeding promotion. Operates the Mothers' Milk Bank in Hyderabad - the first human milk bank in Telangana.",
        "relevance_score": 96.0,
        "priority_score": 93.0,
    },
    {
        "name": "Government General Hospital Vijayawada",
        "type": "Government Hospital",
        "district": "Krishna",
        "state": "Andhra Pradesh",
        "address": "Governorpet, Vijayawada, AP 520002",
        "website": "https://gghvijayawada.ap.gov.in",
        "email": "ggh.vijayawada@ap.gov.in",
        "phone": "+91-866-2571234",
        "description": "Major government hospital serving Krishna district with dedicated maternity ward, obstetrics department, and free maternal health services under JSSK and NHM schemes. Handles over 8000 deliveries annually.",
        "relevance_score": 88.0,
        "priority_score": 85.0,
    },
    {
        "name": "CARE Hospitals Hyderabad",
        "type": "Private Hospital",
        "district": "Hyderabad",
        "state": "Telangana",
        "address": "Road No. 1, Banjara Hills, Hyderabad 500034",
        "website": "https://carehospitals.com",
        "email": "info@carehospitals.com",
        "phone": "+91-40-30418888",
        "description": "Multi-specialty hospital with excellent maternal and fetal medicine department. Performs over 3000 deliveries annually with state-of-the-art NICU facilities. Strong CSR program in maternal health.",
        "relevance_score": 85.0,
        "priority_score": 82.0,
    },
    {
        "name": "Primary Health Centre Narsapur",
        "type": "PHC",
        "district": "West Godavari",
        "state": "Andhra Pradesh",
        "address": "Narsapur, West Godavari, AP",
        "email": "phc.narsapur@ap.gov.in",
        "phone": "+91-8814-222333",
        "description": "Primary health center providing basic maternal and child health services, antenatal care, immunization, and referral services to rural communities in West Godavari district.",
        "relevance_score": 78.0,
        "priority_score": 74.0,
    },
    {
        "name": "Narayana Medical College Nellore",
        "type": "Medical College",
        "district": "Nellore",
        "state": "Andhra Pradesh",
        "address": "Chinthareddypalem, Nellore, AP 524003",
        "website": "https://narayanamedicalcollege.com",
        "email": "info@narayanamedicalcollege.com",
        "phone": "+91-861-2305000",
        "description": "Medical college hospital with comprehensive obstetrics and gynecology department, maternal health research programs, and community outreach initiatives in Nellore district.",
        "relevance_score": 87.0,
        "priority_score": 84.0,
    },
    {
        "name": "Rainbow Hospitals Visakhapatnam",
        "type": "Private Hospital",
        "district": "Visakhapatnam",
        "state": "Andhra Pradesh",
        "address": "MVP Colony, Visakhapatnam, AP 530017",
        "website": "https://rainbowhospitals.in",
        "email": "vizag@rainbowhospitals.in",
        "phone": "+91-891-2700000",
        "description": "Specialized pediatric and women hospital with Level III NICU, fetal medicine unit, and high-risk obstetric care. Serves northern Andhra Pradesh region with 24/7 maternal emergency services.",
        "relevance_score": 90.0,
        "priority_score": 87.0,
    },
    {
        "name": "Mamta Health Institute for Mother & Child",
        "type": "NGO",
        "district": "Hyderabad",
        "state": "Telangana",
        "address": "Somajiguda, Hyderabad, Telangana 500082",
        "website": "https://mamtahimc.org",
        "email": "info@mamtahimc.org",
        "phone": "+91-40-23300733",
        "description": "Dedicated to improving maternal and newborn health through training healthcare providers, community mobilization, and policy advocacy across Telangana. Partners with government on MMR reduction.",
        "relevance_score": 93.0,
        "priority_score": 90.0,
    },
    {
        "name": "SEWA Rural Telangana",
        "type": "NGO",
        "district": "Karimnagar",
        "state": "Telangana",
        "address": "Karimnagar, Telangana 505001",
        "email": "sewa.telangana@gmail.com",
        "phone": "+91-878-2223456",
        "description": "Community-based organization working on rural maternal health, traditional birth attendant training, and linking rural women with government health schemes in Karimnagar district.",
        "relevance_score": 82.0,
        "priority_score": 79.0,
    },
]

SEED_NGOS = [
    {
        "name": "Dhaatri Resource Centre for Women & Children",
        "district": "Hyderabad",
        "state": "Telangana",
        "focus_areas": ["Maternal Health", "Breastfeeding", "Women's Rights", "Nutrition"],
        "website": "https://dhaatri.org",
        "description": "Operates Hyderabad's first Mothers' Milk Bank and advocates for maternal health rights. Strong community networks across Telangana.",
        "alignment_score": 97.0,
    },
    {
        "name": "Mamta Health Institute for Mother & Child",
        "district": "Hyderabad",
        "state": "Telangana",
        "focus_areas": ["Maternal Health", "Newborn Care", "Healthcare Training", "Policy"],
        "website": "https://mamtahimc.org",
        "description": "Works on improving quality of maternal and newborn health care through capacity building of health providers and community awareness.",
        "alignment_score": 95.0,
    },
    {
        "name": "SEWA Rural Telangana",
        "district": "Karimnagar",
        "state": "Telangana",
        "focus_areas": ["Rural Health", "Maternal Care", "Women Empowerment", "Government Schemes"],
        "description": "Links rural women with government maternal health schemes and trains traditional birth attendants on safe delivery practices.",
        "alignment_score": 87.0,
    },
    {
        "name": "Sneha India Foundation",
        "district": "Guntur",
        "state": "Andhra Pradesh",
        "focus_areas": ["Child Health", "Maternal Nutrition", "Anemia Prevention"],
        "website": "https://sneha.org.in",
        "description": "Works on maternal nutrition, anemia prevention in pregnant women, and child health in Andhra Pradesh districts.",
        "alignment_score": 84.0,
    },
    {
        "name": "Prajwala Maternal Health Network",
        "district": "Visakhapatnam",
        "state": "Andhra Pradesh",
        "focus_areas": ["Safe Motherhood", "Antenatal Care", "Community Health Workers"],
        "description": "Network of community health workers providing antenatal care support and safe delivery guidance in tribal areas of Visakhapatnam.",
        "alignment_score": 89.0,
    },
    {
        "name": "Vatsalya Foundation",
        "district": "Hyderabad",
        "state": "Telangana",
        "focus_areas": ["Maternal Mental Health", "Postpartum Care", "Women Support"],
        "website": "https://vatsalya.org",
        "description": "Focuses on maternal mental health, postpartum depression support, and holistic care for new mothers in urban Hyderabad.",
        "alignment_score": 81.0,
    },
]

SEED_FUNDERS = [
    {
        "name": "Bill & Melinda Gates Foundation",
        "type": "Global Foundation",
        "focus_areas": ["Maternal Health", "Child Mortality", "Global Health", "India Programs"],
        "grant_size": "$500K - $5M",
        "geography": "Global / India",
        "website": "https://gatesfoundation.org",
        "description": "Major funder for maternal and newborn health programs in India. Actively funds programs in Andhra Pradesh and Telangana.",
        "relevance_score": 98.0,
    },
    {
        "name": "Tata Trusts",
        "type": "Indian Foundation",
        "focus_areas": ["Maternal Health", "Nutrition", "Rural Health", "Women"],
        "grant_size": "₹10L - ₹2Cr",
        "geography": "India",
        "website": "https://tatatrusts.org",
        "description": "Significant funder for maternal health programs in South India. Runs own maternal health initiatives and funds partner NGOs.",
        "relevance_score": 95.0,
    },
    {
        "name": "UNICEF India",
        "type": "UN Agency",
        "focus_areas": ["Child Health", "Maternal Health", "Nutrition", "WASH"],
        "grant_size": "Variable",
        "geography": "India",
        "website": "https://unicef.org/india",
        "description": "Partners with NGOs and governments on maternal and child health programs. Active in Andhra Pradesh and Telangana.",
        "relevance_score": 93.0,
    },
    {
        "name": "Azim Premji Philanthropic Initiatives",
        "type": "Indian Foundation",
        "focus_areas": ["Health", "Education", "Rural Development"],
        "grant_size": "₹25L - ₹5Cr",
        "geography": "India",
        "website": "https://azimpremjiphilanthropic.org",
        "description": "Funds health and social development programs in South India. Interested in innovative maternal health approaches.",
        "relevance_score": 88.0,
    },
    {
        "name": "CSR - Apollo Hospitals",
        "type": "CSR",
        "focus_areas": ["Maternal Health", "Healthcare Access", "Women Health"],
        "grant_size": "₹5L - ₹50L",
        "geography": "South India",
        "website": "https://apollohospitals.com/csr",
        "description": "Apollo Hospitals CSR focuses on maternal health and healthcare access. Strong presence in AP and Telangana.",
        "relevance_score": 86.0,
    },
    {
        "name": "USAID India",
        "type": "Government Aid",
        "focus_areas": ["Maternal Health", "Family Planning", "Health Systems"],
        "grant_size": "$100K - $2M",
        "geography": "India",
        "website": "https://usaid.gov/india",
        "description": "Funds maternal and reproductive health programs in India. Supports innovative approaches to reducing maternal mortality.",
        "relevance_score": 91.0,
    },
    {
        "name": "Wellcome Trust India",
        "type": "Global Foundation",
        "focus_areas": ["Health Research", "Maternal Health", "AI in Health"],
        "grant_size": "£50K - £2M",
        "geography": "Global / India",
        "website": "https://wellcome.org",
        "description": "Funds health research and innovative health programs. Interested in AI-driven maternal health solutions.",
        "relevance_score": 89.0,
    },
    {
        "name": "CSR - TCS",
        "type": "CSR",
        "focus_areas": ["Digital Health", "Women Health", "AI Healthcare"],
        "grant_size": "₹10L - ₹1Cr",
        "geography": "India",
        "website": "https://tcs.com/sustainability",
        "description": "TCS CSR focuses on digital health and women empowerment. Open to AI-powered maternal health initiatives.",
        "relevance_score": 83.0,
    },
]
